import VideoList from "@/components/VideoList";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

type HomeProps = {
  fileNames: string[];
};

export default function Home({ fileNames }: HomeProps) {
  return (
    <>
      <Head>
        <title>Video Streaming</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            rowGap: "20px",
            alignItems: "center",
            justifyContent: "center",
            minHeight: "100vh",
          }}
        >
          <video
            id="videoPlayer"
            controls
            width={1920}
            style={{ width: "100%", height: "auto" }}
          >
            <source src="/api/videos" type="video/mp4" />
          </video>
          <VideoList fileNames={fileNames} />
        </div>
      </main>
    </>
  );
}

export function getStaticProps() {
  const fs = require("fs");
  const fileNames: string[] = [];

  fs.readdirSync("./videos").forEach((file: string) => {
    fileNames.push(file);
  });

  return {
    props: {
      fileNames,
    },
  };
}
